In [21]:
from numpy import *
arr=array([1,2,3,4,5])
print(arr.dtype)

arr1=linspace(0,15,16)
print(arr1)

arr2 = arange(1,15,2)
print(arr2)

arr3=logspace(1,40,5)
#5 values between 10 to power 0 and 10 to power 40 both inclusive

arr4 = ones(5, int)
print(arr4)

arr5 = ones(5, float)
print(arr5)

arr6 = zeros(5, int)
print(arr6)

arr7 = arr6 + 5
print(arr7)

arr8 = arr5 + arr
print(arr8)

print(sqrt(arr8))
print(sum(arr8))
print(min(arr8))
print(max(arr8))
print(sort(arr8))

#COPY A ARRAY

arr9=arr8
print(arr9)

#address same for both array - point to same array

print(id(arr8))

print(id(arr9))

#shallow copy
arr10=arr8.view()
print(id(arr10)) #same as id of arr8
arr8[1] = 5
print(arr10, arr8) #both value change

#deep copy
arr11=arr8.copy()
print(id(arr11)) #same as id of arr8
arr8[1] = 6
print(arr11, arr8) #value change for only arr8



int32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 1  3  5  7  9 11 13]
[1 1 1 1 1]
[1. 1. 1. 1. 1.]
[0 0 0 0 0]
[5 5 5 5 5]
[2. 3. 4. 5. 6.]
[1.41421356 1.73205081 2.         2.23606798 2.44948974]
20.0
2.0
6.0
[2. 3. 4. 5. 6.]
[2. 3. 4. 5. 6.]
2580470218064
2580470218064
2580470217104
[2. 5. 4. 5. 6.] [2. 5. 4. 5. 6.]
2580469449520
[2. 5. 4. 5. 6.] [2. 6. 4. 5. 6.]
